[package]
workspace = "../.."
name = "keycloak-api-example"
version = "0.1.0"
edition = "2021"

[dependencies]
keycloak-api = { path = ".." }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
color-eyre = "0.5"
